export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const ADD_TO_FAVORITES_SUCCESS = 'ADD_TO_FAVORITES_SUCCESS';
export const ADD_TO_FAVORITES_FAILURE = 'ADD_TO_FAVORITES_FAILURE';

export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';
export const REMOVE_FROM_FAVORITES_SUCCESS = 'REMOVE_FROM_FAVORITES_SUCCESS';
export const REMOVE_FROM_FAVORITES_FAILURE = 'REMOVE_FROM_FAVORITES_FAILURE';

export const GET_USER_FAVORITES = 'GET_USER_FAVORITES';
export const GET_USER_FAVORITES_SUCCESS = 'GET_USER_FAVORITES_SUCCESS';
export const GET_USER_FAVORITES_FAILURE = 'GET_USER_FAVORITES_FAILURE';
