export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';

export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';

export const CANCEL_TOGGLE = 'CANCEL_TOGGLE';
export const CANCEL_TOGGLE_SUCCESS = 'CANCEL_TOGGLE_SUCCESS';
export const CANCEL_TOGGLE_FAILURE = 'CANCEL_TOGGLE_FAILURE';
