export const FETCH_EVENTS = 'FETCH_EVENTS';
export const FETCH_EVENTS_SUCCESS = 'FETCH_EVENTS_SUCCESS';
export const FETCH_EVENTS_FAILURE = 'FETCH_EVENTS_FAILURE';

export const GET_NEXT_EVENTS = 'GET_NEXT_EVENTS';
export const GET_NEXT_EVENTS_SUCCESS = 'GET_NEXT_EVENTS_SUCCESS';
export const GET_NEXT_EVENTS_FAILURE = 'GET_NEXT_EVENTS_FAILURE';

export const CREATE_EVENT = 'CREATE_EVENT';
export const CREATE_EVENT_SUCCESS = 'CREATE_EVENT_SUCCESS';
export const CREATE_EVENT_FAILURE = 'CREATE_EVENT_FAILURE';

export const UPDATE_EVENT = 'UPDATE_EVENT';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const UPDATE_EVENT_FAILURE = 'UPDATE_EVENT_FAILURE';

export const CANCEL_TOGGLE = 'CANCEL_TOGGLE';
export const CANCEL_TOGGLE_SUCCESS = 'CANCEL_TOGGLE_SUCCESS';
export const CANCEL_TOGGLE_FAILURE = 'CANCEL_TOGGLE_FAILURE';

export const UPLOAD_EVENT_IMAGE = 'UPLOAD_EVENT_IMAGE';
export const UPLOAD_EVENT_IMAGE_SUCCESS = 'UPLOAD_EVENT_IMAGE_SUCCESS';
export const UPLOAD_EVENT_IMAGE_FAILURE = 'UPLOAD_EVENT_IMAGE_FAILURE';
