export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE = 'UPDATE_PROFILE_FAILURE';

export const UPLOAD_PHOTO = 'UPLOAD_PHOTO';
export const UPLOAD_PHOTO_SUCCESS = 'UPLOAD_PHOTO_SUCCESS';
export const UPLOAD_PHOTO_FAILURE = 'UPLOAD_PHOTO_FAILURE';

export const DELETE_PHOTO = 'DELETE_PHOTO';
export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';
export const DELETE_PHOTO_FAILURE = 'DELETE_PHOTO_FAILURE';

export const SET_PROFILE_PHOTO = 'SET_PROFILE_PHOTO';
export const SET_PROFILE_PHOTO_SUCCESS = 'SET_PROFILE_PHOTO_SUCCESS';
export const SET_PROFILE_PHOTO_FAILURE = 'SET_PROFILE_PHOTO_FAILURE';

export const JOIN_EVENT = 'JOIN_EVENT';
export const JOIN_EVENT_SUCCESS = 'JOIN_EVENT_SUCCESS';
export const JOIN_EVENT_FAILURE = 'JOIN_EVENT_FAILURE';

export const CANCEL_JOIN_EVENT = 'CANCEL_JOIN_EVENT';
export const CANCEL_JOIN_EVENT_SUCCESS = 'CANCEL_JOIN_EVENT_SUCCESS';
export const CANCEL_JOIN_EVENT_FAILURE = 'CANCEL_JOIN_EVENT_FAILURE';
